import type { Metadata } from "next";
import { Space_Grotesk  } from "next/font/google";
import "./globals.css";
import SidebarComponent from "./components/sidebarComponent";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} h-dvh antialiased `}
    >
      <body className="flex xl:flex-row flex-col h-dvh">
        <SidebarComponent />
        <div className="p-5 h-full w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
