import type { Metadata } from "next";
import { Space_Grotesk  } from "next/font/google";
import "./globals.css";
import SidebarComponent from "./components/sidebarComponent";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} antialiased `}
    >
      <body className="flex xl:flex-row flex-col h-dvh text-sm md:text-base">
        <SidebarComponent />
        <div className="flex flex-col p-5 py-4 h-full w-full overflow-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
